import { AppLanguage } from "../types";

type CopyMap = Record<string, string>;

const en: CopyMap = {
  appTitle: "Daily Verse",
  appSubtitle: "Today’s God’s Word",
  explanation: "Explanation",
  message: "Today’s Message",
  prayer: "Prayer",
  favorite: "Favorite",
  share: "Share",
  refresh: "Refresh",
  history: "History",
  favorites: "Favorites",
  settings: "Settings",
  home: "Home",
  streak: "Reading Streak",
  language: "Language",
  theme: "Theme",
  notificationTime: "Notification Time",
  saveSettings: "Save Settings",
  sendTest: "Send Test Notification",
  sendDaily: "Trigger Daily Push",
  signIn: "Sign In",
  signUp: "Create Account",
  email: "Email",
  name: "Name",
  password: "Password",
  noHistory: "No verses yet. Refresh today’s verse to begin.",
  noFavorites: "No favorites saved yet.",
  remove: "Remove",
  logout: "Logout",
  light: "Light",
  dark: "Dark",
  notificationEnabled: "Daily notifications",
};

const te: CopyMap = {
  appTitle: "డైలీ వర్స్",
  appSubtitle: "ఈరోజు దేవుని వాక్యము",
  explanation: "వివరణ",
  message: "ఈరోజు సందేశం",
  prayer: "ప్రార్థన",
  favorite: "సేవ్",
  share: "షేర్",
  refresh: "రిఫ్రెష్",
  history: "చరిత్ర",
  favorites: "ఫేవరెట్స్",
  settings: "సెట్టింగ్స్",
  home: "హోమ్",
  streak: "నిరంతర పఠనం",
  language: "భాష",
  theme: "థీమ్",
  notificationTime: "నోటిఫికేషన్ సమయం",
  saveSettings: "సేవ్ చేయండి",
  sendTest: "టెస్ట్ నోటిఫికేషన్ పంపు",
  sendDaily: "డైలీ పుష్ ట్రిగ్గర్",
  signIn: "లాగిన్",
  signUp: "ఖాతా సృష్టించండి",
  email: "ఇమెయిల్",
  name: "పేరు",
  password: "పాస్‌వర్డ్",
  noHistory: "ఇంకా వాక్యాలు లేవు. నేడు వాక్యాన్ని రిఫ్రెష్ చేయండి.",
  noFavorites: "ఇంకా ఫేవరెట్స్ లేవు.",
  remove: "తొలగించు",
  logout: "లాగౌట్",
  light: "లైట్",
  dark: "డార్క్",
  notificationEnabled: "రోజువారీ నోటిఫికేషన్స్",
};

export const getCopy = (language: AppLanguage) => (language === "te" ? te : en);

export default getCopy;
